title: "My Notes"
description: "Rina Chenâ€™s living notebook on shaping sensible, empowering narratives of technology that support people and communities."
theme: jekyll-theme-minimal

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Set your Pages URL (project pages)
url: "https://imrinahru.github.io"
baseurl: "/my-site-fresh"

# Let Jekyll convert Markdown files even if they lack front matter
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Give all pages a default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
